project:
  type: book
  output-dir: "docs"
  preview:
    port: 1313
    browser: false
  resources: 
    - "*.html"

execute: 
  freeze: auto
  cache: true
  daemon: 3600

website:
  favicon: "img/logos/favicon.ico"
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Demostraciones de Cálculo Científico con Julia"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2024"
  output-file: "julia-demos"
  image: img/logos/sticker.png
  cover-image: img/logos/sticker.png
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar: 
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  twitter-card: 
    site: "@aprendeconalf"
  chapters:
    - index.qmd
    
#bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme:
      dark: darkly
      light: flatly
    html-math-method: mathjax
    code-overflow: wrap
  pdf:
    documentclass: scrreport
    papersize: a4
    template-partials:
      - before-body.tex
    titlegraphic: img/logos/sticker.png
    institution: CEU San Pablo
    email: asalber@ceu.es
    web: https://aprendeconalf.es
    logo: img/logos/aprendeconalf.png
    include-in-header:
      - preamble.tex
      - macros.tex
    keep-tex: true
    #mainfont: TeX Gyre Termes
    #mainfontoptions:
    #  - Numbers=Lowercase
    #  - Numbers=Proportional    
    
  epub:
    cover-image: img/logos/sticker.png
    html-math-method: mathml
    toc: true



